### PR TITLE
EventQueue_ex_2: dispatch_forever() is more readable than dispatch()

### PR DESCRIPTION
**Pull request by LDong-Arm**
This is needed for https://github.com/ARMmbed/mbed-os-5-docs/pull/1321

### CODE REVIEW

**Comment by hugueskamba** [comment]
Note that @adbridge  script will have to be re-run to create the stand-alone repo for this snippet if it is to be released for Mbed OS 6.

**Comment by LDong-Arm** [comment]
@evedon Can we merge this, because the documentation that depends on this is already merged?

The CI failures are in existing snippets, not this PR's

**Comment by evedon** [comment]
@jamesbeyond Please merge if CI failures are not related to this PR

**Comment by jamesbeyond** [comment]
yes, the Error was because of something else. I'll put separate PR to fix it

**Pull request merged**
