### PR TITLE
Add Network related examples

### PR DESCRIPTION
**Pull request by mprse**

### CODE REVIEW

**Comment by mprse** [comment]
`DATAFLASHBLOCKDEVICE` example fails because it requires `DATAFLASH` to be added to `K64F` components list. This is done via `mbed_app.json` configuration file which is added to the example directory. 
The problem is that `mbed test` probably ignores this file.

**Comment by mprse** [comment]
Solved CI issue. This one is ready to go.

**Comment by jamesbeyond** [comment]
> Solved CI issue. This one is ready to go.

Hey @mprse, thanks for the changes, but sorry I might need to ask you split this PR into 3. because they contain examples of several teams. one PR would be difficult for people to review, and slow down the merge process. 
So I suggested split them into 3:
- NFC related ->PAN team
- Storage -> STORAGE team
- Network and Cellular -> Cellular team

**Comment by mprse** [comment]
@jamesbeyond Split this one as requested:
 NFC related ->PAN team (PR https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/87)
Storage -> STORAGE team (PR https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/86)
Network and Cellular -> Cellular team (this one)

I also added missing headers.

**Comment by jamesbeyond** [comment]
Hi @AnttiKauppila,
could you have a look, see if you happy about those snippets examples, they been moved from https://github.com/ARMmbed/mbed-os-5-docs/blob/development/docs/api/networksocket/CellularNonIPSocket.md#cellularnonipsocket-example
to here

**Comment by mprse** [comment]
Maybe I should change `APIs_networksocket/...` to `APIs_Network/...`. This would be more generic and suitable also for examples like:
https://os.mbed.com/teams/mbed_example/code/TCPSocket_Example/file/50f1485931f1/main.cpp/

**Comment by jamesbeyond** [comment]
> Maybe I should change `APIs_networksocket/...` to `APIs_Network/...`. This would be more generic and suitable also for examples like:
> https://os.mbed.com/teams/mbed_example/code/TCPSocket_Example/file/50f1485931f1/main.cpp/

Maybe `APIs_NetworkSocket/...` with little changes on the caps to match all others? in the documents, it is under `NetworkSocket` page  :
https://os.mbed.com/docs/mbed-os/v5.15/apis/non-ip-cellular-socket.html

**Comment by mprse** [comment]
Rebased and updated directory name as suggested.

**Pull request merged**
