### PR TITLE
Add USB examples

### PR DESCRIPTION
**Pull request by mprse**
This PR adds tested USB examples + description to this repository. Test summary can be found in the table below:

Board | USBSerial | USBAudio square wave | USBAudio loopback | USBAudio wav audio player | USBAudio play sound | USBHID | USBCDC | USBCDC ECM | USBMSD SD | USBMSD heap | USBMIDI | USBMIDI take me out to the   ballgame example | USBMouse absolute | USBMouse relative | USBMouseJoystick | USBKeyboard | USBMouseKeyboard
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
NUCLEO_F429ZI | OK | OK | OK | Not Supported | OK | OK | OK | OK | Not Supported | OK | OK | OK | OK | OK | Don't have joystick | OK | OK
K64F | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK | Don't have joystick | OK | OK
DISCO_L475VG_IOT01A | OK | OK | OK | Not Supported | OK | OK | OK | OK | Not Supported | OK | OK | OK | OK | OK | Don't have joystick | OK | ok
NUCLEO_F411RE | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Don't have joystick | Not Supported | Not Supported
NRF52840_DK | OK | Doesn't work | Doesn't work | Not Supported | Doesn't work | OK | OK | OK | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Don't have joystick | Not Supported | Not Supported
NUCLEO_F303RE | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | OK | OK | OK | OK | OK | Don't have joystick | OK | OK
LPC55S69_NS | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Don't have joystick | Not Supported | Not Supported
NUCLEO_L073RZ | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Not Supported | Don't have joystick | Not Supported | Not Supported

### CODE REVIEW

**Comment by jamesbeyond** [comment]
when possible, could you attached PR of updating the link in `https://github.com/ARMmbed/mbed-os-5-docs` as well

**Comment by mprse** [comment]
This one should be ready to go.
Some examples have been fixed (updated deprecated functions, fixed minor issues). Detailed status can be found in the table provided in the description.

`USBAudio` examples look good but don't work on `NRF52840_DK`. The example works on other boards, so probably further investigation of USBAudio driver for NRF is required.

**Comment by jamesbeyond** [comment]
BTW, could you update the code links in https://github.com/ARMmbed/mbed-os-5-docs, and pointed them to here, and links the PR in here

**Comment by mprse** [comment]
> BTW, could you update the code links in https://github.com/ARMmbed/mbed-os-5-docs, and pointed them to here, and links the PR in here @mprse

Yes, but I thought that to do that first this one needs to be merged. So I'm able to access code/description from this repo.

**Comment by AnotherButler** [comment]
Docs PRs up: https://github.com/ARMmbed/mbed-os-5-docs/pull/1224, https://github.com/ARMmbed/mbed-os-5-docs/pull/1225 and https://github.com/ARMmbed/mbed-os-5-docs/pull/1226/files

**Pull request merged**
