### PR TITLE
add EventQueue deffering example

### PR DESCRIPTION
**Pull request by maciejbocianski**
Move example [events_ex_1](https://os.mbed.com/teams/mbed_example/code/events_ex_1/) to this repoi

fixed:
 - changed Thread::gettid() to ThisThread::get_id()
- changed printf to UnbufferedSerial::write to log from ISR

@jamesbeyond

### CODE REVIEW

**Comment by jamesbeyond** [comment]
Hi @maciejbocianski  could you rebase your branch, the latest repo contains the master version of mbed-os.
Also could you link the Issue which you PR fixing

**Comment by maciejbocianski** [comment]
@jamesbeyond  rebased

**Comment by jamesbeyond** [comment]
Hi @maciejbocianski,
could you update the links in the doc as well:
https://github.com/ARMmbed/mbed-os-5-docs/blob/development/docs/api/rtos/EventQueue.md#eventqueue-example-deferring-from-interrupt-context

**Comment by maciejbocianski** [comment]
Docs link updated https://github.com/ARMmbed/mbed-os-5-docs/pull/1198

**Comment by noritan** [comment]
I cannot access to the UnbufferedSerial class in my Mbed Studio environment.
It is better to use the RawSerial class like:

// It's safe to use UnbufferedSerial in ISR context
RawSerial console(USBTX, USBRX);

void rise_handler(void) {
    console.printf("rise_handler in context %p\n", ThisThread::get_id());
    // Toggle LED
    led1 = !led1;
}

**Comment by jamesbeyond** [comment]
Hi @noritan, 
Technically you are right. in mbed OS 5.15, RawSerial is the one to use.
But this PR is targeting for the next release of mbed OS. where the RawSerial Class is replaced with UnbufferedSerial (This is already happened in the latest master). They are pretty much the same apart from the naming changes. We are making this change mainly for unifying the Serial Classes inside mbed OS. So you when you updating to the latest version of mbed OS please remember of this change

**Pull request merged**
