### PR TITLE
Add NetworkSocket (TCP) examples

### PR DESCRIPTION
**Pull request by mprse**

### CODE REVIEW

**Comment by jamesbeyond** [comment]
Hi @mprse , 
could you change the folder name from `Network` to `NetworkSocket` to match with the documents

**Comment by jamesbeyond** [comment]
@michalpasztamobica , could you have a quick look to confirm if all the snippets are OK, and no deprecated APIs been used ?

**Comment by mprse** [comment]
Rebased the branch on the master.

**Comment by jamesbeyond** [comment]
@mprse Could you rename the the folder from `APIs_Network` to `APIs_NetworkSocket`

**Comment by mprse** [comment]
> @mprse Could you rename the the folder from APIs_Network to APIs_NetworkSocket

Done!

**Pull request merged**
