### PR TITLE
Update Event/EventQueue snippets to mirror updates to the API changes

### PR DESCRIPTION
**Pull request by adbridge**
https://github.com/ARMmbed/mbed-os/pull/13975 updates the EventQueue dispatch API to 
1) move it to using chrono times and bring it inline with the rest of the code
2) Separates the API into 3 distinct functions
    a) dispatch_for(duration ms)
    b) dispatch_once()
    c) dispatch_forever()

This PR updates the example snippets to mirror this functionality.

### CODE REVIEW

**Comment by adbridge** [comment]
NOTE: will not pass the CI until the Mbed OS PR is merged !

**Comment by adbridge** [comment]
Ahh looks like UserAllocatedEvent_ex1 also needs updating - will get than one added now.

**Comment by adbridge** [comment]
Looks like we are going to revisit some of the inconsistencies in the event / event queue APIs and fix them all in one go, thus this PR is on hold for now.

**Comment by adbridge** [comment]
@evedon @0xc0170 please review

**Review by 0xc0170 — APPROVED** [review]

**Review by evedon — APPROVED** [review]
Looks good. 
Please squash your commits before merging.
We also need a green CI after the mbed-os PR is merged.

**Comment by adbridge** [comment]
@0xc0170 looks like we can merge this ?

**Pull request merged**
