### PR TITLE
Delete main.cpp

### PR DESCRIPTION
**Pull request by AnotherButler**
Delete file because it is outdated and no longer used in the documentation.

### CODE REVIEW

**Comment by cmonr** [comment]
@AnotherButler Shouldn't the entire directory be removed instead?

**Comment by AnotherButler** [comment]
Besides this one: https://github.com/ARMmbed/mbed-os-examples-docs_only/pull/34?

**Comment by cmonr** [comment]
Ah, didn't see the other one. Was expecting a PR with the removal together.

**Comment by AnotherButler** [comment]
That would have made sense, but I made separate PRs. And then didn't link them. My bad.

**Pull request merged**
